# Default values for wireguard-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/linuxserver/wireguard
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

server:
  peers:
    - peer1
  env:
    PUID: "1000"
    PGID: "1000"
    TZ: "Europe/London"
    SERVERURL: "auto"
    SERVERPORT: "30000"
    PEERDNS: "auto"
    INTERNAL_SUBNET: "10.13.13.0"
    ALLOWEDIPS: "0.0.0.0/0"
  peers:
    - peer1

configPersistence:
  type: pvc
  pvc:
    # storageClassName:
    accessModes:
      - ReadWriteOnce
    size: 50Mi
    # annotations: {}
    # finalizers: {}
    # existingClaim:

service:
  nodePort: 30000

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
