apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "wireguard-server.fullname" .}}
  labels: {{- include "wireguard-server.labels" . | nindent 4}}
data:
  {{- with .Values.server.env }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.server.peers }}
  PEERS: {{ join "," . | quote }}
  {{- end }}
