apiVersion: v1
kind: Service
metadata:
  name: {{include "wireguard-server.fullname" .}}
  labels: {{- include "wireguard-server.labels" . | nindent 4}}
spec:
  type: NodePort
  ports:
    - port: 51820
      targetPort: 51820
      nodePort: {{.Values.service.nodePort}}
      protocol: UDP
      name: http
  selector: {{- include "wireguard-server.selectorLabels" . | nindent 4}}
